# These are supported funding model platforms

github: it22318466          # GitHub Sponsors
patreon:                    # Patreon username
open_collective:            # Open Collective username
ko_fi:                      # Ko-fi username
tidelift:                   # Tidelift platform-name/package-name
community_bridge:           # Community Bridge project name
liberapay:                  # Liberapay username
issuehunt:                  # IssueHunt username
lfx_crowdfunding:           # LFX Crowdfunding project name
polar:                      # Polar username
buy_me_a_coffee:            # Buy Me a Coffee username
custom:                     # Custom URL(s)
